# Generated by Django 5.0.4 on 2024-04-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='smiley',
            field=models.BooleanField(default=False),
        ),
    ]
