# Generated by Django 5.0.4 on 2024-04-29 11:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_temperature_smiley'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='remarks',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
