# Generated by Django 5.0.4 on 2024-04-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0003_temperature_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
